keys:
  - &admin_jordan age16qkxgvq8z7e3kfexkh9ezp9gqnuh3wgant0uxpu7k6m9925974dqhngj5a
  - &server_hybridhost age1vcr2ewnrn87qr2elkhuf37z6etrqf6tnhdvs6yrgv6fstadxl3msgsfvwh
  - &server_webguest age1pr6v2s7z4xtpcdl4cl5u5r302020auqrxs9mz0c6x39qpww9duvsnzsn6h
creation_rules:
  - path_regex: secrets/webguest/([^/]+\.[^/]+|[^/]+)
    key_groups:
    - age:
      - *admin_jordan
      - *server_webguest
  - path_regex: secrets/common/([^/]+\.[^/]+|[^/]+)
    key_groups:
    - age:
      - *admin_jordan
      - *server_hybridhost
      - *server_webguest
  - path_regex: secrets/hybridhost/([^/]+\.[^/]+|[^/]+)
    key_groups:
    - age:
      - *admin_jordan
      - *server_hybridhost
